# **DATA CLEANING**

In [1]:
import os
import re
import numpy as np
import pandas as pd

In [2]:
data =pd.read_csv("../raw/matches.csv")

In [3]:
data.isna().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [4]:
for i in range(1,len(data["city"])):
    if(pd.isna(data.iat[i,2])):
        data.iat[i,2]="United Arab Emirates"

In [5]:
data.head(1)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen

In [6]:
data.drop(columns="match_type",inplace=True)
data.drop(columns="method",inplace=True)

In [7]:
data.isna().sum()

id                  0
season              0
city                0
date                0
player_of_match     5
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
winner              5
result              0
result_margin      19
target_runs         3
target_overs        3
super_over          0
umpire1             0
umpire2             0
dtype: int64

In [8]:
data.head(1)

,id,season,city,date,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Asad Rauf,RE Koertzen

In [9]:
for i in range(1,len(data["winner"])):
    if(pd.isna(data.iat[i,10])):
        print(i)

241
485
511
744
994

In [10]:
for i in range(1,len(data["result_margin"])):
    if(pd.isna(data.iat[i,10])):
        data.iat[i,10]="No Result"
        data.iat[i,11]="No Result"
        data.iat[i,4]="No Result"

In [11]:
data.iloc[[241,485,511,744,994],:]

,id,season,city,date,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,umpire1,umpire2
241,501265,2011,Delhi,2011-05-21,No Result,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,No Result,No Result,NaN,NaN,NaN,N,SS Hazare,RJ Tucker
485,829763,2015,Bangalore,2015-04-29,No Result,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,No Result,No Result,NaN,NaN,NaN,N,JD Cloete,PG Pathak
511,829813,2015,Bangalore,2015-05-17,No Result,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,No Result,No Result,NaN,188.0,20.0,N,HDPK Dharmasena,K Srinivasan
744,1178424,2019,Bengaluru,2019-04-30,No Result,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,No Result,No Result,NaN,63.0,5.0,N,NJ Llong,UV Gandhe
994,1359519,2023,Lucknow,2023-05-03,No Result,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,No Result,No Result,NaN,NaN,NaN,N,AK Chaudhary,NA Patwardhan

In [12]:
data.isna().sum()

id                  0
season              0
city                0
date                0
player_of_match     0
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
winner              0
result              0
result_margin      19
target_runs         3
target_overs        3
super_over          0
umpire1             0
umpire2             0
dtype: int64

In [13]:
a=[]
for i in range(1,len(data["result_margin"])):
    if(pd.isna(data.iat[i,12])):
        a.append(i)

In [14]:
data=data.fillna(0)
data.iloc[a,:]

,id,season,city,date,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,umpire1,umpire2
66,392190,2009,Cape Town,2009-04-23,YK Pathan,Newlands,Kolkata Knight Riders,Rajasthan Royals,Kolkata Knight Riders,field,Rajasthan Royals,tie,0.0,151.0,20.0,Y,MR Benson,M Erasmus
130,419121,2009/10,Chennai,2010-03-21,J Theron,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,field,Kings XI Punjab,tie,0.0,137.0,20.0,Y,K Hariharan,DJ Harper
241,501265,2011,Delhi,2011-05-21,No Result,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,No Result,No Result,0.0,0.0,0.0,N,SS Hazare,RJ Tucker
328,598004,2013,Hyderabad,2013-04-07,GH Vihari,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Sunrisers Hyderabad,tie,0.0,131.0,20.0,Y,AK Chaudhary,S Ravi
342,598017,2013,Bangalore,2013-04-16,V Kohli,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,Royal Challengers Bangalore,tie,0.0,153.0,20.0,Y,M Erasmus,VA Kulkarni
416,729315,2014,Abu Dhabi,2014-04-29,JP Faulkner,Sheikh Zayed Stadium,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,bat,Rajasthan Royals,tie,0.0,153.0,20.0,Y,Aleem Dar,AK Chaudhary
475,829741,2015,Ahmedabad,2015-04-21,SE Marsh,"Sardar Patel Stadium, Motera",Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,tie,0.0,192.0,20.0,Y,M Erasmus,S Ravi
485,829763,2015,Bangalore,2015-04-29,No Result,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,No Result,No Result,0.0,0.0,0.0,N,JD Cloete,PG Pathak
511,829813,2015,Bangalore,2015-05-17,No Result,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,No Result,No Result,0.0,188.0,20.0,N,HDPK Dharmasena,K Srinivasan
610,1082625,2017,Rajkot,2017-04-29,KH Pandya,Saurashtra Cricket Association Stadium,Gujarat Lions,Mumbai Indians,Gujarat Lions,bat,Mumbai Indians,tie,0.0,154.0,20.0,Y,AK Chaudhary,CB Gaffaney
705,1175365,2019,Delhi,2019-03-30,PP Shaw,Arun Jaitley Stadium,Kolkata Knight Riders,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,tie,0.0,186.0,20.0,Y,AY Dandekar,Nitin Menon
744,1178424,2019,Bengaluru,2019-04-30,No Result,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,No Result,No Result,0.0,63.0,5.0,N,NJ Llong,UV Gandhe
746,1178426,2019,Mumbai,2019-05-02,JJ Bumrah,Wankhede Stadium,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,Mumbai Indians,tie,0.0,163.0,20.0,Y,CK Nandan,S Ravi
757,1216493,2020/21,United Arab Emirates,2020-09-20,MP Stoinis,Dubai International Cricket Stadium,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,Delhi Capitals,tie,0.0,158.0,20.0,Y,AK Chaudhary,Nitin Menon
765,1216547,2020/21,United Arab Emirates,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,0.0,202.0,20.0,Y,Nitin Menon,PR Reiffel
790,1216512,2020/21,Abu Dhabi,2020-10-18,LH Ferguson,Sheikh Zayed Stadium,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kolkata Knight Riders,tie,0.0,164.0,20.0,Y,PG Pathak,S Ravi
791,1216517,2020/21,United Arab Emirates,2020-10-18,KL Rahul,Dubai International Cricket Stadium,Mumbai Indians,Kings XI Punjab,Mumbai Indians,bat,Kings XI Punjab,tie,0.0,177.0,20.0,Y,Nitin Menon,PR Reiffel
835,1254077,2021,Chennai,2021-04-25,PP Shaw,"MA Chidambaram Stadium, Chepauk, Chennai",Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,tie,0.0,160.0,20.0,Y,CB Gaffaney,KN Ananthapadmanabhan
994,1359519,2023,Lucknow,2023-05-03,No Result,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,No Result,No Result,0.0,0.0,0.0,N,AK Chaudhary,NA Patwardhan

In [15]:
data.isna().sum()

id                 0
season             0
city               0
date               0
player_of_match    0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
result_margin      0
target_runs        0
target_overs       0
super_over         0
umpire1            0
umpire2            0
dtype: int64

In [16]:
data.replace(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru']
                ,
             ['RCB','KXIP','DC','MI','KKR','RR','HDC','CSK','KTK','PW','SRH','GL','RPS','RPS','DC','KXIP','LSG','GT','RCB'],inplace=True)
data["team2"].unique()

array(['KKR', 'CSK', 'RR', 'RCB', 'HDC', 'KXIP', 'DC', 'MI', 'KTK', 'PW',
       'SRH', 'RPS', 'GL', 'GT', 'LSG'], dtype=object)

In [17]:
data.to_csv("cleaned_data.csv")