In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
games_data = pd.read_csv("../../data/processed/cleaned_data_deliveries.csv",low_memory=False)

In [3]:
games_data.drop(columns=["Unnamed: 0"],inplace=True)
games_data.tail()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
260915,1426312,2,KKR,SRH,9,5,SS Iyer,AK Markram,VR Iyer,1,...,bat,KKR,wickets,8.0,114.0,20.0,N,No Issues,J Madanagopal,Nitin Menon
260916,1426312,2,KKR,SRH,9,6,VR Iyer,AK Markram,SS Iyer,1,...,bat,KKR,wickets,8.0,114.0,20.0,N,No Issues,J Madanagopal,Nitin Menon
260917,1426312,2,KKR,SRH,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,...,bat,KKR,wickets,8.0,114.0,20.0,N,No Issues,J Madanagopal,Nitin Menon
260918,1426312,2,KKR,SRH,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,...,bat,KKR,wickets,8.0,114.0,20.0,N,No Issues,J Madanagopal,Nitin Menon
260919,1426312,2,KKR,SRH,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,...,bat,KKR,wickets,8.0,114.0,20.0,N,No Issues,J Madanagopal,Nitin Menon

# **Grouping part**

In [4]:
games_data["season"] = games_data["season"].astype("string")
games_data["match_id"] = games_data["match_id"].astype("string")

In [5]:
games_data.groupby("season").get_group("2009").groupby("match_id").count().sort_values("match_id")
games_data.groupby("season").get_group("2024").groupby("match_id").get_group('1422121').iloc[:,0:15]
# a = games_data.groupby("season").get_group("2024")

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed
244312,1422121,1,KKR,SRH,0,1,PD Salt,B Kumar,SP Narine,1,0,1,NaN,0,NaN
244313,1422121,1,KKR,SRH,0,2,SP Narine,B Kumar,PD Salt,0,1,1,wides,0,NaN
244314,1422121,1,KKR,SRH,0,3,SP Narine,B Kumar,PD Salt,0,0,0,NaN,0,NaN
244315,1422121,1,KKR,SRH,0,4,SP Narine,B Kumar,PD Salt,0,0,0,NaN,0,NaN
244316,1422121,1,KKR,SRH,0,5,SP Narine,B Kumar,PD Salt,1,0,1,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244557,1422121,2,SRH,KKR,19,2,H Klaasen,Harshit Rana,Shahbaz Ahmed,1,0,1,NaN,0,NaN
244558,1422121,2,SRH,KKR,19,3,Shahbaz Ahmed,Harshit Rana,H Klaasen,0,0,0,NaN,1,Shahbaz Ahmed
244559,1422121,2,SRH,KKR,19,4,M Jansen,Harshit Rana,H Klaasen,1,0,1,NaN,0,NaN
244560,1422121,2,SRH,KKR,19,5,H Klaasen,Harshit Rana,M Jansen,0,0,0,NaN,1,H Klaasen
244561,1422121,2,SRH,KKR,19,6,PJ Cummins,Harshit Rana,M Jansen,0,0,0,NaN,0,NaN

In [6]:
kyapata=a[(a["batting_team"]=="KKR")&(a["bowling_team"]=="SRH")]["match_id"].drop_duplicates().tolist()

NameError: name 'a' is not defined

In [7]:
games_data[(pd.isna(games_data["dismissal_kind"]))&(pd.isna(games_data["fielder"]))]

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,1,KKR,RCB,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,field,KKR,runs,140.0,223.0,20.0,N,No Issues,Asad Rauf,RE Koertzen
1,335982,1,KKR,RCB,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,field,KKR,runs,140.0,223.0,20.0,N,No Issues,Asad Rauf,RE Koertzen
2,335982,1,KKR,RCB,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,field,KKR,runs,140.0,223.0,20.0,N,No Issues,Asad Rauf,RE Koertzen
3,335982,1,KKR,RCB,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,field,KKR,runs,140.0,223.0,20.0,N,No Issues,Asad Rauf,RE Koertzen
4,335982,1,KKR,RCB,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,field,KKR,runs,140.0,223.0,20.0,N,No Issues,Asad Rauf,RE Koertzen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,KKR,SRH,9,5,SS Iyer,AK Markram,VR Iyer,1,...,bat,KKR,wickets,8.0,114.0,20.0,N,No Issues,J Madanagopal,Nitin Menon
260916,1426312,2,KKR,SRH,9,6,VR Iyer,AK Markram,SS Iyer,1,...,bat,KKR,wickets,8.0,114.0,20.0,N,No Issues,J Madanagopal,Nitin Menon
260917,1426312,2,KKR,SRH,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,...,bat,KKR,wickets,8.0,114.0,20.0,N,No Issues,J Madanagopal,Nitin Menon
260918,1426312,2,KKR,SRH,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,...,bat,KKR,wickets,8.0,114.0,20.0,N,No Issues,J Madanagopal,Nitin Menon
260919,1426312,2,KKR,SRH,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,...,bat,KKR,wickets,8.0,114.0,20.0,N,No Issues,J Madanagopal,Nitin Menon

In [8]:
games_data.groupby("season").get_group("2024").groupby("match_id").get_group('1426312')
games_data.groupby("season").get_group("2024").groupby("match_id").get_group('1426312').groupby("batter").get_group("RA Tripathi").iloc[:,4:20]
# games_data.groupby("season").get_group("2024").groupby("match_id").get_group('1426312').head(10)

,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,season,date,match_type
260741,0,6,RA Tripathi,MA Starc,TM Head,1,0,1,NaN,0,NaN,NaN,NaN,2024,2024-05-26,Final
260742,1,1,RA Tripathi,VG Arora,TM Head,0,0,0,NaN,0,NaN,NaN,NaN,2024,2024-05-26,Final
260743,1,2,RA Tripathi,VG Arora,TM Head,0,0,0,NaN,0,NaN,NaN,NaN,2024,2024-05-26,Final
260744,1,3,RA Tripathi,VG Arora,TM Head,0,0,0,NaN,0,NaN,NaN,NaN,2024,2024-05-26,Final
260745,1,4,RA Tripathi,VG Arora,TM Head,0,2,2,legbyes,0,NaN,NaN,NaN,2024,2024-05-26,Final
260746,1,5,RA Tripathi,VG Arora,TM Head,1,0,1,NaN,0,NaN,NaN,NaN,2024,2024-05-26,Final
260748,2,1,RA Tripathi,MA Starc,AK Markram,4,0,4,NaN,0,NaN,NaN,NaN,2024,2024-05-26,Final
260749,2,2,RA Tripathi,MA Starc,AK Markram,1,0,1,NaN,0,NaN,NaN,NaN,2024,2024-05-26,Final
260754,3,1,RA Tripathi,VG Arora,AK Markram,0,1,1,wides,0,NaN,NaN,NaN,2024,2024-05-26,Final
260755,3,2,RA Tripathi,VG Arora,AK Markram,0,1,1,wides,0,NaN,NaN,NaN,2024,2024-05-26,Final
260756,3,3,RA Tripathi,VG Arora,AK Markram,1,0,1,NaN,0,NaN,NaN,NaN,2024,2024-05-26,Final
260759,3,6,RA Tripathi,VG Arora,AK Markram,0,0,0,NaN,0,NaN,NaN,NaN,2024,2024-05-26,Final
260760,3,7,RA Tripathi,VG Arora,AK Markram,0,1,1,wides,0,NaN,NaN,NaN,2024,2024-05-26,Final
260761,3,8,RA Tripathi,VG Arora,AK Markram,1,0,1,NaN,0,NaN,NaN,NaN,2024,2024-05-26,Final
260763,4,1,RA Tripathi,MA Starc,AK Markram,0,0,0,NaN,0,NaN,NaN,NaN,2024,2024-05-26,Final
260764,4,2,RA Tripathi,MA Starc,AK Markram,0,0,0,NaN,1,RA Tripathi,caught,Ramandeep Singh,2024,2024-05-26,Final

In [12]:
def name_of_game(year,team1,team2,id):
    game_details = games_data.groupby("season").get_group(year).groupby("match_id").get_group(id)
    #Date
    date = game_details["date"].drop_duplicates().tolist()[0]
    print("The Game: {} vs {} on {} id {}".format(team1,team2,date,id))
    innings_1 = games_data.groupby("season").get_group(year).groupby("match_id").get_group(id).groupby("inning").get_group(1)
    print("INNING 1:")
    print("The batting team {} scored {} runs".format(innings_1["batting_team"].iloc[0],innings_1["total_runs"].sum()))
    print("The bowling team {} took {} wickets".format(innings_1["bowling_team"].iloc[0],innings_1["player_dismissed"].count()))
    print()
    players = innings_1["batter"].unique()
    for x in players:
        player_inning = innings_1.groupby("batter")
        
        runs_made = player_inning.get_group(x)["total_runs"].sum()-player_inning.get_group(x)["extra_runs"].sum()
        balls_played = player_inning.get_group(x).shape[0]-player_inning.get_group(x)["extras_type"].value_counts().get("wides",0)
        no_of_fours = player_inning.get_group(x)["batsman_runs"].value_counts().get(4,0)
        no_of_six = player_inning.get_group(x)["batsman_runs"].value_counts().get(6,0)
        strike_rate = (runs_made / balls_played) * 100
        strike_rate = round(strike_rate,2)
        out_bowler = player_inning.get_group(x)["bowler"].iloc[-1]
        out_method = player_inning.get_group(x)["dismissal_kind"].iloc[-1]
        out_by = player_inning.get_group(x)["fielder"].iloc[-1]
        if (out_method == "bowled" or out_method == "lbw" ):
            print("{}:{}:{}:{}:{}:{}   {}::{}".format(x,runs_made,balls_played,no_of_fours,no_of_six,strike_rate,out_method,out_bowler))
        else:
            print("{}:{}:{}:{}:{}:{}   {}::{}".format(x,runs_made,balls_played,no_of_fours,no_of_six,strike_rate,out_method,out_by))


    
    print()
    print()



    
    innings_2 = games_data.groupby("season").get_group(year).groupby("match_id").get_group(id).groupby("inning").get_group(2)
    print("INNING 2:")
    print("The batting team {} scored {} runs".format(innings_2["batting_team"].iloc[0],innings_2["total_runs"].sum()))
    print("The bowling team {} took {} wickets".format(innings_2["bowling_team"].iloc[0],innings_2["player_dismissed"].count()))
    print()

    players = innings_2["batter"].unique()
    for x in players:
        player_inning = innings_2.groupby("batter")
        
        runs_made = player_inning.get_group(x)["total_runs"].sum()-player_inning.get_group(x)["extra_runs"].sum()
        balls_played = player_inning.get_group(x).shape[0]-player_inning.get_group(x)["extras_type"].value_counts().get("wides",0)
        no_of_fours = player_inning.get_group(x)["batsman_runs"].value_counts().get(4,0)
        no_of_six = player_inning.get_group(x)["batsman_runs"].value_counts().get(6,0)
        strike_rate = (runs_made / balls_played) * 100
        strike_rate = round(strike_rate,2)
        out_method = player_inning.get_group(x)["dismissal_kind"].iloc[-1]
        out_bowler = player_inning.get_group(x)["bowler"].iloc[-1]
        out_by = player_inning.get_group(x)["fielder"].iloc[-1]
        if (out_method == "bowled" or out_method == "lbw" ):
            print("{}:{}:{}:{}:{}:{}   {}::{}".format(x,runs_made,balls_played,no_of_fours,no_of_six,strike_rate,out_method,out_bowler))
        else:
            print("{}:{}:{}:{}:{}:{}   {}::{}".format(x,runs_made,balls_played,no_of_fours,no_of_six,strike_rate,out_method,out_by))
            
    
    
    print()
    print()
    

def game_info(year,team1,team2):
    game_of_years = games_data.groupby("season").get_group(year)
    games_of_teams =game_of_years[(game_of_years["batting_team"]==team1)&(game_of_years["bowling_team"]==team2)]["match_id"].drop_duplicates().tolist()
    # for x in games_of_teams:
    name_of_game(year,team1,team2,games_of_teams[-1])
    
game_info("2024","SRH","KKR")

The Game: SRH vs KKR on 2024-05-26 id 1426312
INNING 1:
The batting team SRH scored 113 runs
The bowling team KKR took 10 wickets

Abhishek Sharma:2:5:0:0:40.0   bowled::MA Starc
RA Tripathi:9:13:1:0:69.23   caught::Ramandeep Singh
TM Head:0:1:0:0:0.0   caught::Rahmanullah Gurbaz
AK Markram:20:23:3:0:86.96   caught::MA Starc
Nithish Kumar Reddy:13:10:1:1:130.0   caught::Rahmanullah Gurbaz
H Klaasen:16:17:1:0:94.12   bowled::Harshit Rana
Shahbaz Ahmed:8:7:0:1:114.29   caught::SP Narine
Abdul Samad:4:4:0:0:100.0   caught::Rahmanullah Gurbaz
PJ Cummins:24:19:2:1:126.32   caught::MA Starc
JD Unadkat:4:11:0:0:36.36   lbw::SP Narine
B Kumar:0:1:0:0:0.0   nan::nan


INNING 2:
The batting team KKR scored 114 runs
The bowling team SRH took 2 wickets

Rahmanullah Gurbaz:39:32:5:2:121.88   lbw::Shahbaz Ahmed
SP Narine:6:2:0:1:300.0   caught::Shahbaz Ahmed
VR Iyer:52:26:4:3:200.0   nan::nan
SS Iyer:6:3:1:0:200.0   nan::nan